# This file was generated by GoReleaser. DO NOT EDIT.
class GaSandbox < Formula
  desc "A test for goreleaser."
  homepage "https://github.com/TimothyStiles/poly"
  version "0.11"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/TimothyStiles/ga-sandbox/releases/download/v0.11/ga-sandbox_Darwin_x86_64.tar.gz"
    sha256 "550d0207d1b514ceb1dc23b0e419433c1342edf9297f1de16cb016046ddc955b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/TimothyStiles/ga-sandbox/releases/download/v0.11/ga-sandbox_Linux_x86_64.tar.gz"
      sha256 "baf26a9f9d6066e3191bb95de7575e81884a3adf1c61fca9334781a497e460ba"
    end
  end
  
  depends_on "go"

  def install
    bin.install "ga-sandbox"
  end

  test do
    system "#{bin}/poly -h"
  end
end
